name: Main

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]

jobs:
  pre-commit:
    name: Precommit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: pre-commit/action@v2.0.0
  create-and-publish-docs:
    name: Create Documentation
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          # environment-file: environments/footings-idi-model-dev.yml
          # activate-environment: footings-idi-model-dev
          auto-activate-base: True # False
      - name: Conda info
        run: |
          conda info
          conda list
      - name: Install conda-lock
        run: |
          conda install --channel conda-forge conda-lock
      - name: Create environment and activate
        run: |
          conda create -n footings-idi-model-dev --file environments/footings-idi-model-linux-64.lock
          conda activate footings-idi-model-dev
      - name: Install footings library
        run: |
          pip install footings==0.10.0rc0
      - name: Run sphinx
        run:  nox -s create_docs
      - name: Deploy docs to github pages - master
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/_build
          destination_dir: ./master
      - name: Deploy docs to github pages - dev
        if: github.ref == 'refs/heads/dev'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/_build
          destination_dir: ./dev
